galaxy_info:
  author: PerceptiLabs
  description: Deploys docker to ubuntu
  company: PerceptiLabs
  license:  CC-BY-4.0
  min_ansible_version: 2.10
  platforms:
  - name: Ubuntu
    versions:
    - 16
    - 17
    - 18
    - 19
    - 20
  galaxy_tags:
    - system
    - docker
dependencies: []

