---
- name: "Set up the docker creds if they're not already there"
  hosts: localhost
  gather_facts: no
  tasks:
    - stat:
        path: docker_creds.yaml
      register: stat_result
    - when: not stat_result.stat.exists
      block:
        - pause:
            prompt: Enter the docker repo username
          register: docker_user_entry
        - pause:
            prompt: Enter the docker repo password
            echo: no
          register: docker_pwd_entry
        - copy:
            dest: docker_creds.yaml
            content: "{{ {'x': docker_user_entry.user_input, 'y': docker_pwd_entry.user_input} | to_nice_yaml }}"

- hosts: all
  roles:
    - role: nvidiadocker

- hosts: all
  vars:
    docker_tag: 0.11.10-GPU
    docker_registry_url: perceptilabsenterprise.azurecr.io
  tasks:
    - include_vars:
        file: docker_creds.yaml

    - name: Creating plabs dir
      file:
        state: directory
        path: "{{ ansible_user_dir }}/plabs"
        mode: 0777

    - name: Sending docker-compose.yml file
      template:
        src: docker-compose.yml.j2
        dest: "{{ ansible_user_dir }}/docker-compose.yml"

    - name: Log in to docker repo
      community.docker.docker_login:
        username: "{{ docker_username }}"
        registry_url: "{{ docker_registry_url }}"
        password: "{{ docker_password }}"
        state: present

    - name: Start the tool
      community.docker.docker_compose:
        state: present
        project_src: "{{ ansible_user_dir }}"

    - debug:
        msg: "The tool is ready at http://{{ inventory_hostname }}:8080"
