galaxy_info:
  author: PerceptiLabs
  description: Deploys the PerceptiLabs modeling tool on ubuntu
  company: PerceptiLabs
  license:  private
  min_ansible_version: 2.10
  platforms:
  - name: Ubuntu
    versions:
    - 16
dependencies:
  - nvidiadocker
