---
- name: restart docker
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: remove hello world
  community.docker.docker_image:
    name: hello-world
    state: absent
    force_absent: yes

