---
- import_tasks: tasks/set_drivers_version.yaml
- when: nvidia_driver_version|d('', true)|length == 0
  block:
  - name: Check Ubuntu Release between 16.04 and 19.04
    assert:
      that:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_version is version('16.04', '>=')
        - ansible_distribution_version is version('19.04', '<=')
      fail_msg: The supported NVIDIA drivers require Ubuntu 16.04-19.04. Got {{ ansible_distribution_version }}

    # Makes sure the nvidia_gpu_present fact is set
  - import_tasks: tasks/get_gpu_presence.yaml

  - import_tasks: tasks/do_installation.yaml
    when: nvidia_gpu_present and nvidia_driver_version is undefined

    # makes sure the nvidia_driver_version fact is set
  - import_tasks: tasks/set_drivers_version.yaml

